#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("StepCounter.Resource", IsApplication=true)]

namespace StepCounter
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7F010000
			public const int cadence_names = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int cadence_names_km = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int cadence_values = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int history_spinner = 2130771971;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F020000
			public const int ab_white = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int blue_background = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int red_background = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int white = 2130837507;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7F030000
			public const int paddingBottom = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int standard_padding = 2130903041;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F040000
			public const int ic_action_social_share = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int ic_highscore = 2130968577;
			
			// aapt resource value: 0x7F040002
			public const int ic_launcher = 2130968578;
			
			// aapt resource value: 0x7F040003
			public const int ic_notification = 2130968579;
			
			// aapt resource value: 0x7F040004
			public const int ic_unsupporteddevice = 2130968580;
			
			// aapt resource value: 0x7F040005
			public const int ic_warning = 2130968581;
			
			// aapt resource value: 0x7F040006
			public const int wear_background = 2130968582;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F050001
			public const int calories = 2131034113;
			
			// aapt resource value: 0x7F050002
			public const int completed = 2131034114;
			
			// aapt resource value: 0x7F050003
			public const int counter_layout = 2131034115;
			
			// aapt resource value: 0x7F050004
			public const int day = 2131034116;
			
			// aapt resource value: 0x7F050005
			public const int distance = 2131034117;
			
			// aapt resource value: 0x7F050006
			public const int fragment_host = 2131034118;
			
			// aapt resource value: 0x7F050007
			public const int high_score = 2131034119;
			
			// aapt resource value: 0x7F050008
			public const int main_layout = 2131034120;
			
			// aapt resource value: 0x7F050009
			public const int menu_history = 2131034121;
			
			// aapt resource value: 0x7F05000A
			public const int menu_settings = 2131034122;
			
			// aapt resource value: 0x7F05000B
			public const int menu_share = 2131034123;
			
			// aapt resource value: 0x7F05000C
			public const int no_sensor_box = 2131034124;
			
			// aapt resource value: 0x7F05000D
			public const int no_sensor_image = 2131034125;
			
			// aapt resource value: 0x7F05000E
			public const int no_step_sensor = 2131034126;
			
			// aapt resource value: 0x7F05000F
			public const int percentage = 2131034127;
			
			// aapt resource value: 0x7F050010
			public const int progressView = 2131034128;
			
			// aapt resource value: 0x7F050000
			public const int RelativeLayout1 = 2131034112;
			
			// aapt resource value: 0x7F050011
			public const int remaining = 2131034129;
			
			// aapt resource value: 0x7F050013
			public const int stepcount = 2131034131;
			
			// aapt resource value: 0x7F050014
			public const int steps = 2131034132;
			
			// aapt resource value: 0x7F050012
			public const int step_count = 2131034130;
			
			// aapt resource value: 0x7F050015
			public const int today = 2131034133;
			
			// aapt resource value: 0x7F050016
			public const int top_layer = 2131034134;
			
			// aapt resource value: 0x7F050017
			public const int warning = 2131034135;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F060000
			public const int history = 2131099648;
			
			// aapt resource value: 0x7F060001
			public const int item_history = 2131099649;
			
			// aapt resource value: 0x7F060002
			public const int main = 2131099650;
			
			// aapt resource value: 0x7F060003
			public const int simple_spinner_item_1 = 2131099651;
			
			// aapt resource value: 0x7F060004
			public const int simple_spinner_item_2 = 2131099652;
			
			// aapt resource value: 0x7F060005
			public const int step_entry = 2131099653;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7F070000
			public const int history = 2131165184;
			
			// aapt resource value: 0x7F070001
			public const int main = 2131165185;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F080000
			public const int about = 2131230720;
			
			// aapt resource value: 0x7F080001
			public const int about_title = 2131230721;
			
			// aapt resource value: 0x7F080002
			public const int app_name = 2131230722;
			
			// aapt resource value: 0x7F080003
			public const int awesome = 2131230723;
			
			// aapt resource value: 0x7F080004
			public const int awesome_title = 2131230724;
			
			// aapt resource value: 0x7F080005
			public const int cadence = 2131230725;
			
			// aapt resource value: 0x7F080006
			public const int cadence0 = 2131230726;
			
			// aapt resource value: 0x7F080007
			public const int cadence0_km = 2131230727;
			
			// aapt resource value: 0x7F080008
			public const int cadence1 = 2131230728;
			
			// aapt resource value: 0x7F080009
			public const int cadence1_km = 2131230729;
			
			// aapt resource value: 0x7F08000A
			public const int cadence2 = 2131230730;
			
			// aapt resource value: 0x7F08000B
			public const int cadence2_km = 2131230731;
			
			// aapt resource value: 0x7F08000C
			public const int cadence3 = 2131230732;
			
			// aapt resource value: 0x7F08000D
			public const int cadence3_km = 2131230733;
			
			// aapt resource value: 0x7F08000E
			public const int cadence4 = 2131230734;
			
			// aapt resource value: 0x7F08000F
			public const int cadence4_km = 2131230735;
			
			// aapt resource value: 0x7F080010
			public const int cadence5 = 2131230736;
			
			// aapt resource value: 0x7F080011
			public const int cadence5_km = 2131230737;
			
			// aapt resource value: 0x7F080012
			public const int cadence6 = 2131230738;
			
			// aapt resource value: 0x7F080013
			public const int cadence6_km = 2131230739;
			
			// aapt resource value: 0x7F080014
			public const int calories = 2131230740;
			
			// aapt resource value: 0x7F080015
			public const int calories_short = 2131230741;
			
			// aapt resource value: 0x7F080016
			public const int category_general_preferences = 2131230742;
			
			// aapt resource value: 0x7F080017
			public const int category_notifications_preferences = 2131230743;
			
			// aapt resource value: 0x7F080018
			public const int completed = 2131230744;
			
			// aapt resource value: 0x7F080019
			public const int copyright = 2131230745;
			
			// aapt resource value: 0x7F08001A
			public const int created_by = 2131230746;
			
			// aapt resource value: 0x7F08001B
			public const int created_by_summary = 2131230747;
			
			// aapt resource value: 0x7F08001C
			public const int created_with = 2131230748;
			
			// aapt resource value: 0x7F08001D
			public const int created_with_summary = 2131230749;
			
			// aapt resource value: 0x7F08001E
			public const int custom_step_goal = 2131230750;
			
			// aapt resource value: 0x7F08001F
			public const int enhanced = 2131230751;
			
			// aapt resource value: 0x7F080020
			public const int enhanced_summary = 2131230752;
			
			// aapt resource value: 0x7F080021
			public const int goal_double = 2131230753;
			
			// aapt resource value: 0x7F080022
			public const int goal_full = 2131230754;
			
			// aapt resource value: 0x7F080023
			public const int goal_half = 2131230755;
			
			// aapt resource value: 0x7F080024
			public const int goal_update = 2131230756;
			
			// aapt resource value: 0x7F080025
			public const int has_been_reset = 2131230757;
			
			// aapt resource value: 0x7F080026
			public const int high_score = 2131230758;
			
			// aapt resource value: 0x7F080027
			public const int high_score_title = 2131230759;
			
			// aapt resource value: 0x7F080028
			public const int inspired_by = 2131230760;
			
			// aapt resource value: 0x7F080029
			public const int inspired_by_summary = 2131230761;
			
			// aapt resource value: 0x7F08002A
			public const int kilometeres = 2131230762;
			
			// aapt resource value: 0x7F08002B
			public const int menu_history = 2131230763;
			
			// aapt resource value: 0x7F08002C
			public const int menu_settings = 2131230764;
			
			// aapt resource value: 0x7F08002D
			public const int menu_share = 2131230765;
			
			// aapt resource value: 0x7F08002E
			public const int miles = 2131230766;
			
			// aapt resource value: 0x7F08002F
			public const int month = 2131230767;
			
			// aapt resource value: 0x7F080032
			public const int notifications_accumulative = 2131230770;
			
			// aapt resource value: 0x7F080033
			public const int notifications_accumulative_summary = 2131230771;
			
			// aapt resource value: 0x7F080034
			public const int notifications_progress = 2131230772;
			
			// aapt resource value: 0x7F080035
			public const int notifications_progress_summary = 2131230773;
			
			// aapt resource value: 0x7F080030
			public const int no_history = 2131230768;
			
			// aapt resource value: 0x7F080031
			public const int no_step_sensor = 2131230769;
			
			// aapt resource value: 0x7F080036
			public const int ok = 2131230774;
			
			// aapt resource value: 0x7F080037
			public const int percent_complete = 2131230775;
			
			// aapt resource value: 0x7F080038
			public const int reset_count = 2131230776;
			
			// aapt resource value: 0x7F080039
			public const int reset_high_score = 2131230777;
			
			// aapt resource value: 0x7F08003A
			public const int review_app = 2131230778;
			
			// aapt resource value: 0x7F08003B
			public const int review_app_summary = 2131230779;
			
			// aapt resource value: 0x7F08003C
			public const int share_steps_on = 2131230780;
			
			// aapt resource value: 0x7F08003D
			public const int share_steps_today = 2131230781;
			
			// aapt resource value: 0x7F08003E
			public const int share_steps_total = 2131230782;
			
			// aapt resource value: 0x7F08003F
			public const int steps = 2131230783;
			
			// aapt resource value: 0x7F080040
			public const int steps_cap = 2131230784;
			
			// aapt resource value: 0x7F080041
			public const int today = 2131230785;
			
			// aapt resource value: 0x7F080042
			public const int total = 2131230786;
			
			// aapt resource value: 0x7F080043
			public const int version = 2131230787;
			
			// aapt resource value: 0x7F080044
			public const int week = 2131230788;
			
			// aapt resource value: 0x7F080045
			public const int weight_kg = 2131230789;
			
			// aapt resource value: 0x7F080046
			public const int weight_lbs = 2131230790;
			
			// aapt resource value: 0x7F080047
			public const int weight_title_kg = 2131230791;
			
			// aapt resource value: 0x7F080048
			public const int weight_title_lbs = 2131230792;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F090000
			public const int MyTheme = 2131296256;
			
			// aapt resource value: 0x7F090001
			public const int MyTheme_ActionBar = 2131296257;
			
			// aapt resource value: 0x7F090002
			public const int MyTheme_ActionBar_TitleTextStyle = 2131296258;
			
			// aapt resource value: 0x7F090003
			public const int ThemeActionBar = 2131296259;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7F0A0000
			public const int preferences_general = 2131361792;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
	}
}
#pragma warning restore 1591
